"""Add suspension fields to Post model

Revision ID: 9c6b7b142ab9
Revises: eb0899f8d421
Create Date: 2025-07-25 17:18:13.868278

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c6b7b142ab9'
down_revision = 'eb0899f8d421'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_suspended', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('suspended_until', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_column('suspended_until')
        batch_op.drop_column('is_suspended')

    # ### end Alembic commands ###
