"""Add author_nickname to Post and Comment models

Revision ID: 30cc120e58f4
Revises: c9abfd0242fc
Create Date: 2025-07-18 17:14:57.180339

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '30cc120e58f4'
down_revision = 'c9abfd0242fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('author_nickname', sa.String(length=80), nullable=True))
        batch_op.alter_column('likes',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
        batch_op.drop_column('author_username')
        batch_op.drop_column('display_author_name')

    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('author_nickname', sa.String(length=80), nullable=True))
        batch_op.alter_column('is_anonymous',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
        batch_op.alter_column('views',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
        batch_op.alter_column('likes',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
        batch_op.drop_column('author_username')
        batch_op.drop_column('display_author_name')

    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=80),
               existing_nullable=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['nickname'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.String(length=80),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=False)

    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('display_author_name', mysql.VARCHAR(length=80), nullable=True))
        batch_op.add_column(sa.Column('author_username', mysql.VARCHAR(length=80), nullable=False))
        batch_op.alter_column('likes',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
        batch_op.alter_column('views',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
        batch_op.alter_column('is_anonymous',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
        batch_op.drop_column('author_nickname')

    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('display_author_name', mysql.VARCHAR(length=80), nullable=True))
        batch_op.add_column(sa.Column('author_username', mysql.VARCHAR(length=80), nullable=False))
        batch_op.alter_column('likes',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
        batch_op.drop_column('author_nickname')

    # ### end Alembic commands ###
