"""Add display_author_name to Comment model

Revision ID: 3dbc51d494a4
Revises: 8508234e00c3
Create Date: 2025-07-15 17:28:50.777222

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3dbc51d494a4'
down_revision = '8508234e00c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('display_author_name', sa.String(length=80), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_column('display_author_name')

    # ### end Alembic commands ###
