"""Add views column to Post model

Revision ID: 8508234e00c3
Revises: 9ad6ebc789ac
Create Date: 2025-07-15 16:36:40.382988

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8508234e00c3'
down_revision = '9ad6ebc789ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('views', sa.Integer(), nullable=False))
        batch_op.alter_column('mongodb_content_id',
               existing_type=mysql.VARCHAR(length=24),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.alter_column('mongodb_content_id',
               existing_type=mysql.VARCHAR(length=24),
               nullable=False)
        batch_op.drop_column('views')

    # ### end Alembic commands ###
