"""Add category, is_anonymous, display_author_name to posts table

Revision ID: 9ad6ebc789ac
Revises: 378ce3f599d6
Create Date: 2025-07-15 14:46:41.121236

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9ad6ebc789ac'
down_revision = '378ce3f599d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # NOTE: 'post_attachments' 테이블이 현재 모델에 정의되어 있지 않으므로,
    # 해당 테이블이 존재하지 않을 경우를 대비하여 삭제 명령을 주석 처리합니다.
    # 만약 이전에 이 테이블이 존재했고 이제 삭제하려는 의도라면, 이 줄의 주석을 해제할 수 있습니다.
    # op.drop_table('post_attachments')


    # 1. 'posts' 테이블의 변경사항을 먼저 적용하여 외래 키 제약 조건 및 컬럼을 제거합니다.
    #    이는 'post_categories' 테이블을 삭제하기 전에 반드시 선행되어야 합니다.
    with op.batch_alter_table('posts', schema=None) as batch_op:
        # 기존 'category_id'와 관련된 외래 키 삭제
        # 'posts_ibfk_2'는 Alembic이 자동으로 생성한 외래 키 이름일 가능성이 높습니다.
        # 만약 마이그레이션 실패 시 이 이름이 다를 수 있습니다.
        batch_op.drop_constraint(batch_op.f('posts_ibfk_2'), type_='foreignkey')
        batch_op.drop_column('category_id')

        # 새로운 컬럼 추가
        batch_op.add_column(sa.Column('category', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('is_anonymous', sa.Boolean(), nullable=False))
        # 'display_author_name' 컬럼을 models.py와 일치하도록 nullable=True로 변경
        batch_op.add_column(sa.Column('display_author_name', sa.String(length=80), nullable=True))

        # 기존 'title' 컬럼의 타입 변경
        batch_op.alter_column('title',
               existing_type=mysql.VARCHAR(length=200),
               type_=sa.String(length=255),
               existing_nullable=False)

        # 'mongodb_content_id'에 고유 제약 조건 추가
        # (이 부분이 이미 존재하면 오류 발생 가능, 그럴 경우 이 줄을 주석 처리해야 함)
        batch_op.create_unique_constraint(None, ['mongodb_content_id'])


    # 2. 'posts' 테이블에서 참조가 모두 제거된 후 'post_categories' 테이블을 삭제합니다.
    #    이전에 오류를 발생시킨 인덱스 삭제 명령은 여전히 주석 처리되어 있어야 합니다.
    with op.batch_alter_table('post_categories', schema=None) as batch_op:
        # 이전에 오류를 발생시킨 인덱스 삭제 명령을 주석 처리합니다.
        # 테이블을 삭제하면 인덱스도 자동으로 삭제됩니다.
        # batch_op.drop_index(batch_op.f('name'))
        pass # 빈 블록 오류 방지를 위해 'pass' 추가

    op.drop_table('post_categories')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('posts_ibfk_2'), 'post_categories', ['category_id'], ['id'])
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('title',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=200),
               existing_nullable=False)
        batch_op.drop_column('display_author_name')
        batch_op.drop_column('is_anonymous')
        batch_op.drop_column('category')

    op.create_table('post_categories',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=80), nullable=False),
    sa.Column('description', mysql.TEXT(), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('post_categories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('name'), ['name'], unique=True)

    op.create_table('post_attachments',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('post_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('file_name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('file_path', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('file_type', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], name=op.f('post_attachments_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###